services:
    oro_alternativecheckout.conditions.less_order_total_limit:
        class: 'Oro\Bundle\AlternativeCheckoutBundle\Condition\OrderTotalLimit'
        arguments:
            - '@oro_pricing.subtotal_processor.total_processor_provider'
            - '@oro_checkout.data_provider.manager.checkout_line_items'
        tags:
            - { name: oro_action.condition, alias: less_order_total_limit }

    oro_alternativecheckout.block_type.extension.checkout_form_fields:
        parent: oro_layout.block_type.extension.abstract_configurable
        calls:
            - [setOptionsConfig, [{transitionData: ~}]]
            - [setExtendedType, ['checkout_form_fields']]
        tags:
            - { name: layout.block_type_extension, alias: checkout_form_fields }

    oro_alternativecheckout.datagrid.extension.frontend_shopping_list_grid.abstract:
        abstract: true
        class: Oro\Bundle\CheckoutBundle\Datagrid\FrontendShoppingListGridExtension
        arguments:
            -
                - 'frontend-customer-user-shopping-lists-grid'
                - 'frontend-customer-user-shopping-list-select-grid'
            -
                - 'b2b_flow_alternative_checkout_start_from_shoppinglist'

    oro_alternativecheckout.datagrid.extension.frontend_shopping_list_grid.before_actions:
        parent: oro_alternativecheckout.datagrid.extension.frontend_shopping_list_grid.abstract
        arguments:
            - '-250'
        tags:
            - { name: oro_datagrid.extension }

    oro_alternativecheckout.datagrid.extension.frontend_shopping_list_grid.after_actions:
        parent: oro_alternativecheckout.datagrid.extension.frontend_shopping_list_grid.abstract
        arguments:
            - '250'
        tags:
            - { name: oro_datagrid.extension }

    oro_alternativecheckout.workflow.transition.go_back:
        class: Oro\Bundle\AlternativeCheckoutBundle\Workflow\Transition\GoBack
        arguments:
            - '@oro_checkout.action_group.update_shipping_price'
        tags:
            - { name: oro_workflow.transition_service }

    oro_alternativecheckout.workflow.transition.continue_to_request_approval:
        class: Oro\Bundle\AlternativeCheckoutBundle\Workflow\Transition\ContinueToRequestApproval
        arguments:
            - '@oro_action.action_executor'
        tags:
            - { name: oro_workflow.transition_service }

    oro_alternativecheckout.workflow.transition.approve_order:
        class: Oro\Bundle\AlternativeCheckoutBundle\Workflow\Transition\ApproveOrder
        arguments:
            - '@oro_action.action_executor'
        tags:
            - { name: oro_workflow.transition_service }

    oro_alternativecheckout.workflow.transition.request_for_approve_order:
        class: Oro\Bundle\AlternativeCheckoutBundle\Workflow\Transition\RequestForApproveOrder
        arguments:
            - '@oro_action.action_executor'
        tags:
            - { name: oro_workflow.transition_service }

    oro_alternativecheckout.workflow.transition.place_order:
        class: Oro\Bundle\AlternativeCheckoutBundle\Workflow\Transition\PlaceOrder
        arguments:
            - '@oro_checkout.workflow.b2b_flow_checkout.transition.place_order'
            - '@oro_action.action_executor'
        tags:
            - { name: oro_workflow.transition_service }
