imports:
    -
        resource: '@OroCheckoutBundle/Resources/config/oro/workflows/b2b_flow_checkout.yml'
        workflow: b2b_flow_checkout
        as: b2b_flow_alternative_checkout
        replace: ['exclusive_active_groups', 'defaults', 'steps.order_review.allowed_transitions']

workflows:
    b2b_flow_alternative_checkout:
        priority: 100

        defaults:
            active: false

        scopes:
            - { customer: 4 }

        variable_definitions:
            variables:
                order_approval_threshold:
                    type: 'float'
                    value: 5000
                    options:
                        form_options:
                            constraints:
                                NotBlank: ~
                            tooltip: true

        attributes:
            # Extends the list of attributes of the b2b_flow_checkout.attributes
            allowed:
                type: bool
            allow_request_date:
                type: object
                options:
                    class: DateTime
            requested_for_approve:
                type: bool
            request_approval_notes:
                type: string

        steps:
            order_review:
                # Overrides b2b_flow_checkout.steps.order_review.allowed_transitions
                allowed_transitions:
                    - verify_customer_consents
                    - continue_to_request_approval
                    - place_order
                    - verify_payment
                    - finish_checkout
                    - payment_error
                    - paid_partially
                    - back_to_enter_credentials
                    - back_to_customer_consents
                    - back_to_billing_address
                    - back_to_shipping_address
                    - back_to_shipping_method
                    - back_to_payment
                    - back_to_shipping_address_on_fail_address
            request_approval:
                order: 80
                allowed_transitions:
                    - verify_customer_consents
                    - continue_to_approve_request
                    - back_to_enter_credentials
                    - back_to_customer_consents
                    - back_to_billing_address
                    - back_to_shipping_address
                    - back_to_shipping_method
                    - back_to_payment
                    - back_to_shipping_address_on_fail_address
                    - back_to_order_review
            approve_request:
                order: 90
                allowed_transitions:
                    - verify_customer_consents
                    - approve_order
                    - verify_payment
                    - finish_checkout
                    - payment_error
                    - place_order_with_inactive_possibility
                    - back_to_enter_credentials
                    - back_to_customer_consents
                    - back_to_billing_address
                    - back_to_shipping_address
                    - back_to_shipping_method
                    - back_to_payment
                    - back_to_shipping_address_on_fail_address
                    - back_to_order_review
                    - back_to_request_approval
            order_created:
                # Overrides b2b_flow_checkout.steps.order_created.order
                order: 100

        transitions:
            place_order:
                # Overrides Overrides b2b_flow_checkout.transitions.place_order.transition_service
                transition_service: 'oro_alternativecheckout.workflow.transition.place_order'

            continue_to_request_approval:
                step_to: request_approval
                transition_service: 'oro_alternativecheckout.workflow.transition.continue_to_request_approval'
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_continue: true
                form_options:
                    attribute_fields:
                        remove_source: ~
                        po_number: ~
                        ship_until:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\CheckoutShipUntilType
                            options:
                                checkout: $checkout
                        customer_notes:
                            form_type: Symfony\Component\Form\Extension\Core\Type\TextareaType
                            options:
                                data: $checkout.customerNotes

            continue_to_approve_request:
                step_to: approve_request
                transition_service: 'oro_alternativecheckout.workflow.transition.request_for_approve_order'
                frontend_options:
                    is_checkout_continue: true
                form_options:
                    attribute_fields:
                        request_approval_notes:
                            form_type: Symfony\Component\Form\Extension\Core\Type\TextareaType
                            options:
                                data: $request_approval_notes
                message_parameters:
                    '{{ value }}': $.data.order_approval_threshold

            back_to_order_review:
                step_to: order_review
                transition_service: 'oro_alternativecheckout.workflow.transition.go_back'
                frontend_options:
                    is_checkout_back: true

            back_to_request_approval:
                step_to: request_approval
                transition_service: 'oro_alternativecheckout.workflow.transition.go_back'
                frontend_options:
                    is_checkout_back: true

            place_order_with_inactive_possibility:
                step_to: approve_request
                transition_service: 'oro_alternativecheckout.workflow.transition.place_order'
                display_type: page
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                form_options:
                    attribute_fields:
                        remove_source: ~

            approve_order:
                step_to: approve_request
                transition_service: 'oro_alternativecheckout.workflow.transition.approve_order'
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
